spring:
  application:
    name: Spring RabbitMQ Demo
  rabbitmq:
    username: myuser
    password: secret
demo:
  rabbitmq:
    queue-name: simpleQueueNext
    topic-exchange-name: default-exchange
    routing-key: simple.routing.#
    sender:
      exchange: default-exchange
      routing-key: simple.routing.lol.kek
  file:
    receiver-directory-path: C:\Programming\demo\spring-rabbit-mq-demo\Spring RabbitMQ Demo\receiver-directory
    received-file-name: simple-file
    rabbitmq:
      fanout-queue-name: simple.fanout.queue.name
      fanout-topic-exchange-name: simple.topic.exchange.name
    sender:
      fanout-sender-exchange: simple.topic.exchange.name
