spring:
  application:
    name: Spring RabbitMQ Demo
  rabbitmq:
    username: myuser
    password: secret
demo:
  rabbitmq:
    queueName: simpleQueueNext
    topicExchangeName: default-exchange
    routingKey: simple.routing.#
    sender:
      exchange: default-exchange
      routingKey: simple.routing.lol.kek
